# Generated by Django 3.1.2 on 2020-10-17 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChmicalPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=100)),
                ('chemical_percenatege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_test.chemicalelement')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inventory', models.FloatField(verbose_name='Tons')),
                ('price', models.FloatField(verbose_name='price')),
                ('chemical_manymany', models.ManyToManyField(to='sms_test.ChmicalPercentage')),
            ],
        ),
    ]
