# Generated by Django 3.1.2 on 2020-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chmicalpercentage',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
