# Generated by Django 3.1.2 on 2020-10-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_test', '0003_auto_20201017_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chmicalpercentage',
            old_name='name_1',
            new_name='name',
        ),
    ]
