# Generated by Django 3.1.2 on 2020-10-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_test', '0004_auto_20201017_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='chemical_manymany',
        ),
        migrations.AddField(
            model_name='chemicalelement',
            name='percentage',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity',
            name='chemical_percantage_manymany',
            field=models.ManyToManyField(to='sms_test.ChemicalElement'),
        ),
    ]
