# Generated by Django 3.1.2 on 2020-10-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_test', '0005_auto_20201017_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='chemical_percantage_manymany',
        ),
        migrations.AddField(
            model_name='commodity',
            name='chemical_manymany',
            field=models.ManyToManyField(to='sms_test.ChmicalPercentage'),
        ),
    ]
