# Generated by Django 3.1.2 on 2020-10-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_test', '0006_auto_20201017_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('dob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_test.dob')),
            ],
        ),
    ]
